"""
Tracking vector
"""

# Internal
from src.core.utils import load_config
from src.models.vit.vit import STViT
from scripts.dataset import SpatialTemporalDataset, skip_missing_collate_fn


# External
from sklearn.manifold import TSNE

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from pathlib import Path
import torch.nn.functional as F
from datetime import datetime
import math
import numpy as np
import matplotlib.pyplot as plt

# ----- CONFIG ----- #
correction_logit = math.log(600)
out_path = Path('exports', 'tsne')
# ------------------ #

# ---- Helper F ---- #
def load_trained_model(cfg_model : nn.Module, cfg_data, model_path, device):
    model = STViT(
        num_dynamic_channels=cfg_model['num_dynamic_channels'],
        num_static_channels=cfg_model['num_static_channels'] + cfg_model['num_single_dynamic_channels'],
        num_timestamps_per_sample=cfg_data['temporal_extent']['sample_extent'],
        patch_size=cfg_model['patch_size'],
        embedding_dim=cfg_model['embedding_dim']
    )
    model.load_state_dict(torch.load(model_path, map_location=device))
    return model.to(device)


def evaluate_model_tsne(model, dataloader: DataLoader):
    model.eval()

    # This will hold a list of dictionaries, one for each timestamp
    time_frames = []

    with torch.no_grad():
        for batch_idx, batch in enumerate(dataloader):
            print(f'Processing test batch_idx {batch_idx + 1} / {len(dataloader)}')
            if batch is None:
                continue

            static_x = batch['static'].to(device)
            single_dynamic_x = batch['single_dynamic'].to(device)
            dynamic_x = batch['dynamic'].to(device)
            
            # Read the timestamp for this specific frame
            date_str = batch['meta_first_date'][0] 
            date_obj = datetime.strptime(date_str, '%Y-%m-%d')

            ## Predict
            pred_map, x_2d = model(
                x_static=static_x,
                x_dynamic=dynamic_x,
                x_single_dynamic=single_dynamic_x,
                return_tokens = True
            )

            grid_h, grid_w = x_2d.shape[2], x_2d.shape[3]

            # Adaptive pooling to match patch resolution
            patch_preds = F.adaptive_avg_pool2d(pred_map, (grid_h, grid_w))
            patch_probabilities = torch.sigmoid(patch_preds - correction_logit)

            # --- PRESERVE STRUCTURES ---
            # Keep both flattened (for t-SNE) and 2D spatial layouts (for geographic plotting)
            # Embeddings: [39, 20, 256] -> flattened to [780, 256]
            embeddings_spatial = x_2d.squeeze(0).permute(1, 2, 0).cpu().numpy()
            embeddings_flat = embeddings_spatial.reshape(-1, 256)
            
            # Predictions: [39, 20] -> flattened to [780]
            preds_spatial = patch_probabilities.squeeze(0).squeeze(0).cpu().numpy()
            preds_flat = preds_spatial.reshape(-1)

            # Package this specific time frame
            frame_data = {
                'date': date_obj,
                'date_str': date_str,
                'embeddings_flat': embeddings_flat,      # Shape: (780, 256)
                'embeddings_spatial': embeddings_spatial, # Shape: (39, 20, 256)
                'predictions_flat': preds_flat,          # Shape: (780,)
                'predictions_spatial': preds_spatial      # Shape: (39, 20)
            }
            
            time_frames.append(frame_data)

    # Sort chronologically by date just in case the dataloader shuffled things
    time_frames.sort(key=lambda x: x['date'])
    
    return time_frames

# ----- Plot F ----- #
def track_single_patch(time_frames, patch_idx, grid_h=39, grid_w=20, perplexity=30):
    """
    Tracks a single patch index across all available timeframes in an integrated vector space.
    
    Parameters:
    -----------
    time_frames : list of dict
        The chronologically sorted list of dictionaries generated by evaluate_model_tsne.
    patch_idx : int
        The flattened index of the target patch to track (must be between 0 and (grid_h * grid_w) - 1).
    grid_h : int, default=39
        The height layout grid dimension.
    grid_w : int, default=20
        The width layout grid dimension.
    perplexity : int, default=30
        The perplexity hyperparameter for the t-SNE manifold fitting.
    """
    num_patches_per_day = grid_h * grid_w
    if not (0 <= patch_idx < num_patches_per_day):
        raise ValueError(f"patch_idx {patch_idx} is out of bounds for a {grid_h}x{grid_w} grid layout.")

    # 1. Calculate 2D spatial matrix coordinates for reference text
    row = patch_idx // grid_w
    col = patch_idx % grid_w
    
    print(f"Isolating Patch Index {patch_idx} (Spatial Matrix Location: Row {row}, Col {col})")
    print(f"Stacking data for global manifold reduction across {len(time_frames)} timeframes...")

    # 2. Extract and pool ALL patches from ALL times to create a cohesive background space
    all_embeddings = np.concatenate([frame['embeddings_flat'] for frame in time_frames], axis=0)
    all_predictions = np.concatenate([frame['predictions_flat'] for frame in time_frames], axis=0)

    # 3. Fit a global t-SNE manifold model
    print("Fitting global t-SNE manifold... (This may take a moment depending on the timeline length)")
    tsne = TSNE(n_components=2, perplexity=perplexity, init='pca', random_state=42)
    global_2d = tsne.fit_transform(all_embeddings)

    # 4. Extract the target patch's historical trajectory coordinates out of the pool
    patch_history_2d = []
    patch_predictions = []
    patch_dates = []

    for idx, frame in enumerate(time_frames):
        # Calculate exactly where this patch falls in the stacked global array
        global_pool_idx = (idx * num_patches_per_day) + patch_idx
        
        patch_history_2d.append(global_2d[global_pool_idx])
        patch_predictions.append(frame['predictions_flat'][patch_idx])
        patch_dates.append(frame['date_str'])

    patch_history_2d = np.array(patch_history_2d)
    patch_predictions = np.array(patch_predictions)

    # 5. Plotting the visualization
    plt.figure(figsize=(11, 9))
    
    # Draw a low-opacity global background context map using all collected patches
    plt.scatter(
        global_2d[:, 0], global_2d[:, 1], 
        c=all_predictions, cmap='coolwarm', alpha=0.07, s=4, label='Vector Space Context'
    )

    # Draw sequential line segments connecting the chronological path steps
    plt.plot(
        patch_history_2d[:, 0], patch_history_2d[:, 1], 
        color='black', linewidth=1.5, linestyle='-', alpha=0.6, zorder=2
    )
    
    # Add small tracking directional arrows along the path
    for i in range(len(patch_history_2d) - 1):
        plt.annotate(
            '', 
            xy=(patch_history_2d[i+1, 0], patch_history_2d[i+1, 1]), 
            xytext=(patch_history_2d[i, 0], patch_history_2d[i, 1]),
            arrowprops=dict(arrowstyle="->", color="black", alpha=0.4, lw=1.5),
            zorder=3
        )

    # Overlay the specific patch instances over time, colored by their prediction risk value
    scatter = plt.scatter(
        patch_history_2d[:, 0], patch_history_2d[:, 1], 
        c=patch_predictions, cmap='YlOrRd', edgecolor='black', 
        s=80, linewidths=1.2, zorder=4, label='Tracked Patch Timeline'
    )

    # Annotate chronological landmark tags (Start and End of Timeline)
    plt.text(
        patch_history_2d[0, 0], patch_history_2d[0, 1] + 1, 
        f" START ({patch_dates[0]})", color='black', fontsize=10, fontweight='bold', zorder=5
    )
    plt.text(
        patch_history_2d[-1, 0], patch_history_2d[-1, 1] + 1, 
        f" END ({patch_dates[-1]})", color='black', fontsize=10, fontweight='bold', zorder=5
    )

    # Aesthetic Polish
    plt.title(f"Temporal Vector Space Trajectory: Patch {patch_idx} (Row {row}, Col {col})", fontsize=14, pad=15)
    plt.xlabel("t-SNE Coordinate 1", fontsize=11)
    plt.ylabel("t-SNE Coordinate 2", fontsize=11)
    plt.colorbar(scatter, label='Burn Risk Probability Value')
    plt.legend(loc='upper left')
    plt.grid(True, linestyle=':', alpha=0.5)
    
    plt.show()
    
    return patch_history_2d, patch_predictions


def plot_global_vector_space(time_frames, perplexity=30, max_display_points=30000):
    """
    Plots all patches across all timeframes in a single global t-SNE manifold.
    Every point is large, solid, and explicitly color-coded from Blue (Safe) to Red (High Risk).
    """
    print(f"Stacking data for global manifold reduction across {len(time_frames)} timeframes...")

    # 1. Pool ALL patches across all timeframes
    all_embeddings = np.concatenate([frame['embeddings_flat'] for frame in time_frames], axis=0)
    all_predictions = np.concatenate([frame['predictions_flat'] for frame in time_frames], axis=0)
    
    total_points = all_embeddings.shape[0]
    print(f"Total patch points collected: {total_points}")

    # 2. Fit the global t-SNE manifold
    print("Fitting global t-SNE manifold...")
    tsne = TSNE(n_components=2, perplexity=perplexity, init='pca', random_state=42)
    global_2d = tsne.fit_transform(all_embeddings)

    # 3. Subsample to prevent points from completely piling on top of each other
    if total_points > max_display_points:
        print(f"Subsampling display down to {max_display_points} points for visual space clarity...")
        indices = np.random.choice(total_points, max_display_points, replace=False)
        plot_2d = global_2d[indices]
        plot_preds = all_predictions[indices]
    else:
        plot_2d = global_2d
        plot_preds = all_predictions

    # 4. Generate the Visualization
    plt.figure(figsize=(12, 10), facecolor='white')
    
    # Render points with larger size and near-solid opacity so colors are perfectly distinct
    scatter = plt.scatter(
        plot_2d[:, 0], plot_2d[:, 1], 
        c=plot_preds, 
        cmap='jet',         # Blue (0% Risk) -> Green -> Yellow -> Solid Red (100% Risk)
        alpha=0.95,         # Solid colors that do not fade out
        s=5.0,             # Much larger point footprint so color is instantly readable
        edgecolors='none'   
    )

    # 5. Aesthetic and Colorbar adjustments
    plt.title("Global Mapping of STViT Latent Feature Space", fontsize=14, pad=15, fontweight='bold')
    plt.xlabel("t-SNE Coordinate 1", fontsize=11)
    plt.ylabel("t-SNE Coordinate 2", fontsize=11)
    
    # Custom Colorbar Setup
    cbar = plt.colorbar(scatter, pad=0.02, extend='both')
    cbar.set_label('Burn Risk Probability Scale', fontsize=12, labelpad=10)
    
    # Set explicit percentage labels on the colorbar
    ticks = cbar.get_ticks()
    cbar.set_ticks(ticks)
    cbar.ax.set_yticklabels([f'{x*100:.0f}% Risk' for x in ticks])

    plt.grid(True, linestyle=':', alpha=0.5, color='gray')
    plt.tight_layout()
    fig_name = 'tsne_glob.png'
    file_path = out_path / fig_name
    plt.savefig(file_path, dpi = 300)
    plt.show()

    return global_2d, all_predictions

# ------ MAIN ------ #
if __name__ == '__main__':
    # Load cfg
    exp_name = 't010_1' # 't009_1'

    cfg_file = 'config_' + exp_name + '.yaml'
    cfg_path = Path('files', 'configs', cfg_file)
    cfg = load_config(cfg_path)
    cfg_model = cfg['model']
    cfg_data = cfg['data']

    # Load model path
    model_path = Path('files', 'experiments', exp_name, f'{exp_name}_model_best.pt')

    # Device
    device = 'mps'

    # Select baseline model
    model = load_trained_model(
        cfg_model=cfg_model,
        cfg_data=cfg_data,
        model_path=model_path,
        device = device
    )

    # Data
    dataset = SpatialTemporalDataset(cfg_path, split_type="val", benchmark_mode=False)
    dataloader = DataLoader(
        dataset, batch_size=1, shuffle=False, num_workers=1,
        pin_memory=False, collate_fn=skip_missing_collate_fn
    )


    time_frames = evaluate_model_tsne(model = model, dataloader=dataloader)

    #track_single_patch(time_frames, patch_idx= 330)
    plot_global_vector_space(time_frames=time_frames)