#import "../template.typ": *

= Conclusions <chap:conclusion>

== Synthesis of Research Objectives

The here discussed investigation has shown that the spatio-temporal vision transformer architecure is highly capable of synthesizing a diverse set of input information. The model structure has successfully learnt the capacity to synthesize information from a wide array of backgrounds to model wildfire trends both in the short-term via multi-day prediction lead-times but also in the seasonal scope, having proven clear ability to capture drought periods and wildfire scarce winter months. Similarly, the model correctly identifies natural barriers as rivers and water. The architecture furthermore successfully shows that the integration of explicit static dataset tags as well as spatial and temporal embeddings are a highly effective in forming an understanding of underlying trends. 

Additionally notable for the general conceptualization of this work, is the conceptualization of the target which predicitons are compared to. The transformer architecture demonstrates the transition from a binary, deterministic ground truth to a probabalistic prediction. This in addition with a highly weighted loss function proves that the model is able to abstract information from historical burn records and infer at different locations. 

Prediction accuracy does not lineraly increase with the amount of context provided as input. A model with a single day of data input extent, which thereofore operates outside of the scope of the temporal transformer, showed to be inferior to more contextualized versions. Under the current framework, the transformer model opeartes more proficiently when explicitly encoding temporal features, however only to a certain extent. Overcontextualization has shown to overcomplicate the predictive mechanism resulting in higher error. A three-day sample extent strikes the best balance between stable performance and practical generalizability. From the temporal perspective, there are yet some applications the here presented architecture does not cater to. Most notably the extension of a daily perspective to a yearly view of risk, especially a predictive one, is not possible under computational restraints. 

The performance of model predictions degregades with elongated lead-times. The longer the predictive horizon shifts into the future, the more difficult it becomes for the model to project its current characterization multiple days aheaad. While capturing immediate context is possible under the current framework, longer-term trends have here only been captured implicitly via the quasi-static features (e.g. precipitation 30 day sum). The results obtained in the investigations of both sample extent and lead time point to the necessity to contextualize data modules deeper throughout history in order to present more valid long-term future predictions.

Feature impact can effectively be studied via ablation methods. By utilizing a constrained-model approach and limiting its input features, the reliance of predictions via error tracking can effectively be quantified. Perhaps more importantly, this proves the model to behaving as desired: it leverages the landscape of multi-modal inputs rather than finding mathematical shortcuts in the inherent noise of the data. Seasonal ablation studies have found the model to be mainly reliant on LST, especially in the summer months as the dynamic driver. On the other side, terrain features carry the most predictive influence. Also highly notable is the superiority of NDWI over NDVI as an impactful moisture metric. Feature impact, also in part due to lobsided occurrence of fire in summer, is highly seasonal. When predicting low probabilities, the model outputs rely more equally on all input features. 

// Embedding a single wildfire feature space, storing facts about the phenomenon than about the data.
As conjected in the introductory sections, applying the spatio-temporal transformer to natural catastrophe research has shown good ability for high dimensional embedding vector spaces to capture dense knowledge on climate conditions. It reasons not simply from data alone, but from conglomerated knowledge from combinations of data modules.


== Contributions
The fusion and explicit encoding of both positions and time via embeddings was the main focus of this work and throughout has proven to be a valuable approach for contextualizing multi-model satellite imagery. By architecutre design presents a successful implementation of an early fusion approach allowing data from all spatial and temporal coordinates to freely communicate. 

The transition from a deterministic binary ground truth to a probabalistic interpretation of risk is to be highlighted. The successful inference of risk into regions without sufficient burn history is a good addition to wildfire mitigation strategies. Furthermore, the methodology proves to be a working approach to transition from modelling risk of fire ignition and the thereon dependent spread, towards a pure risk of occurrence approach. 

== Future Work & Recommendations
Enriching a transformer model with more diverse input data modules, while coming at the cost of computational load, will improve prediction accuracy to the extent of its novelty to the existing data. The results shown in the ablation study provide the clear feedback from the model, that less important features will simply be scaled down regardless. Allthough the investigation here focused on the holistic natural science view of satellite data, including socioeconomic data such as GDP density can be valuable additions to the framework. 

As refined in the results section, the main limiting factor is the relationship of the number of input tokens to computational load: $O(n_"token"^2)$. Possible alleviations of these effects include sliding-window attention or even cuboid attention which involve temporal concatenation of rasters into blocks rather than patches. Further enhancing geo-spatial and temporal context opens up possibility for a wide array of prediction scenarios. Sufficient amounts of data are already available and with apt harmonization techniques allow drough and wildfire risk to not be tracked over days but contextualized and tracked over years. The novelty of such an approach would reach even closer into the root cause of increased wildfire activity, the changing climate. 