#import "../template.typ": *


= Introduction <chap:intro>

== Context <sec:context>

// Wildfires and their emerging threats
Perhaps one of the most impactful emerging challenges is the increasing threat of natural disasters, in particular wildfires. The California wildfires of 2025 represent the costliest natural disaster in the history of the United States with some estimates reaching 275 Billion USD. The biggest contributors were the Palisades and Eaton fires with events igniting almost simultaneously, making emergency resource management and mitigation measures extremely difficult to coordinate. Experts argue that a combination of neglected vegetation management, strong prevailing winds and forest health issues were at the core of an event that ultimately destroyed 9594 hectares and over 6800 structures @palisades. Between 2024 and 2025, total Carbon emissions related to fire rose 9% above the yearly average. As temperature averages reach new maxima year after year, the correlated frequency of wildfires shift with it. In Southern California, estimates quantify the total burnt area to be as much as 25 times larger as a direct consequence of the changing climate. In Northeast Amazonia, extreme fire weather is up to 70 times more likely as a result @stateofwildfires. 

== Remote Sensing in Wildfire Modelling <sec:rm_wildfires>
// How geographic data is relevant within modeling and quantifying wildfire
A great deal of scientific effort has been invested to make preparedness for wildfire risk a data-driven discipline. While historically experts relied on environmental assumptions @rothermel to gain knowledge on envirnomental conditions, we today have an abundance of data freely available and powerful computational methods to analyze them. With satellite imagery being publically distributed in accessible formats, physical phenomena like natural hazards may be detected, tracked and characterized from afar without expert knowledge of the on-site conditions.

// Approaches to RS wildfire modeling
The spatial and temporal coverage of satellite data coincides well with the threats posed by natural hazards as these are highly stochastic and globally relevant. While local knowledge used to be required to characterize fire fuel conditions, these can in todays time be monitored from afar. Deep learning methods in particular require large datasets for training, making satellite-collected remote sensing data the ideal discipline that has found great success in a variety of applications. 

Since applying ML in the wildfire realm, the focus has shifted from guiding mitigation via reaction to also using prediction as a counter measure. The difficulty with providing valuable wildfire risk quantifications arises directly from heterogeneity of the data underlying these effects. The combination of static images (e.g. topography, land use) and dynamic variables (e.g. NDVI, land surface temperature). 

Approaches, amongst others, included deep neural networks and long-short-term memory setups, which lied on sequential nature of timer-series data to capture their information about physical processes @durlevic. It is however exactly this sequentialism which poses as the mainbottleneck. These networks inherently, while being able to memorize and learn short-term information, the longer the input sequences to be predicted are, the worse the predictions become. The same effect is apparent for convolutions, which characterize convolutional neural netoworks. These excell at capturing local features, however struggle distant relationships. Being able to capture temporal and spatial relationships is crucial for wildfire modeling.


== Vision Transformers for Wildfire Prediction
// Transformers
Transformers address this isssue as the data processed is permutation invariant as it is inherently encoded in each input token @attention. Having proven to be effective in both image classification @transformer-image and time-series forecasting @transformer-forecasting, it is apparent that transformers cater perfectly to the problem setup of wildfire prediction, as it can learn an understanding of deep physical processes as well as the inherent meaning of space-time. Furthermore, transformers cater precisely to the latent space blind spot by sequentially-based architecutres, as they operate entirely in parallel. Additionally to being able to explicitly encode spatial dimensions in transformer models, time can be handled analogously, alleviating the issue of vanishing information in long sequences. Finally, the transformer handles its computations in parallel, making it highly scalable.

Much research has been done into integrating such spatio-temporal transformers in wildfire related topics, especially for predicting wildfire spread @jain-ml-overview. The high susceptibility of an ignited fire to wind, terrain and drought indices have proven the spatio-temporal setup to be quite useful in predicting spread directions, thus serving public authorities as a valuable tool. 

== Problem Statement <sec:problem>
Despite being an established method for predictive methods in a variety of sectors, one of which being wildfire prediction, little work has been done into treating wildfire occurrence separately from risk of ignition and its consequent spread. The spatio-temporal transformer leverages a highly parallelizable, efficient framework, with the ability to learn a variety of tasks. With the ability to process and denote explicity the spatial and temporal dependencies of data modularities in combination with spaital attention blocks, the wide availability of multi-modal satellite becomes an asset. The approach of this investigation relies on fusion of both static and dynamic environmental datasets, as well as explicit infusion of spatial and temporal embedding of space-time. Together with historical records of burnt area as ground truth, we form a predictive pipeline between environmental data and reality which specifically targets the generalized risk of wildfire occurrence.

This report is structured as follows: @chap:related_work reviews the most important related work into drivers of wildfire, an introduction to the spatio-temporal transformer architecture, as well as existing studies applying it to wildfire scenarios. Most importantly, the research questions guiding this work and experiments that make up the investigation are explained. In @chap:methodology an account of the methodology used to construct datasets, the overall structure of training as well as details regarding the proposed spatio-temporal transformer model architecture are given. Results of all experiments as well as a discussion into all research questions and experiments is presented in @chap:results before a concise summary in @chap:conclusion.