
author = "Carlo Cordes"
title = "Spatio-temporal Transformers for Wildfire Risk Prediction"
graduation-year = 2026
graduation-month = "June"
supervisor1 = "Dr. Azarakhsh Rafiee"
supervisor2 = "Justin Schembri"
coreader    = "Dr. Simona Bianchi"
#graduation-group = "3D geoinformation group"
graduation-group = "Geo-Database Management Centre"

