
author = "Carlo Cordes"
title = "The optimal Delaunay triangulation of cheesy songs"
graduation-year = 2026
graduation-month = "June"
supervisor1 = "Dr. Azarakhsh Rafiee"
supervisor2 = "Justin Schembrie"
coreader    = "tbd"
#graduation-group = "3D geoinformation group"
graduation-group = "Geo-Database Management Centre"

