data:
  spatial_extent:
    longmin: -9.4900
    longmax: -6.0234
    latmin: 36.812
    latmax: 42.2724
  crs: "EPSG:3763"
  scale: 1000 # meters

  temporal_extent:
    start_date: "2023-01-01"
    end_date: "2025-12-31"
    day_interval: 1

    sequence_period : 4 # Time between respective sequences

    sample_extent : 10 # Total time of sample
    sample_period : 1 # Time between images in sample

    target_extent : 7

    lead_time : 0 # Time between last sample and target



model: 
  num_modules: 2
  embedding_dim: 128
  patch_size: 8 # Pixels
  dir: 'data/models'

training:
  learning_rate: 0.0001
  num_epochs: 1
  pos_weight : 200
  batch_size: 4
  num_splits : 10

  train_size : 0.7
  val_size : 0.15
  test_size : 0.15

  patience : 15


data_paths:
  raw:
    target : 'data/raw/target_zarr'
    uncertainty : 'data/raw/uncertainty'
    DTM : 'data/raw/elevation'
    roads : 'data/raw/roads'
  processed:
    roads : 'data/processed/roads'
    LST : 'data/processed/LST'
    NDVI : 'data/processed/NDVI'
    NDWI : 'data/processed/NDWI'
    precip : 'data/processed/precip'
    wind_speed : 'data/processed/wind_speed'
    wind_dir_u : 'data/processed/wind_dir_WE'
    wind_dir_v : 'data/processed/wind_dir_SN'
    slope : 'data/processed/slope'
    aspect : 'data/processed/aspect'
    burn_history : 'data/processed/burn_history'
    target: 'data/processed/target'

    

data_sets:
  path: "data/datasets"