data:
  spatial_extent:
    longmin: -9.4900
    longmax: -6.0234
    latmin: 36.812
    latmax: 42.2724
  crs: "EPSG:3763"
  scale: 1000 # meters

  temporal_extent:
    start_date: "2022-01-01"
    end_date: "2024-01-31"
    day_interval: 8

model: 
  num_modules: 2
  embedding_dim: 256
  patch_size: 16 # Pixels
  dir: 'data/models'

training:
  learning_rate: 0.0001
  num_epochs: 20
  loss_function : "weighted_bce" # "mse"
  pos_weight : 80
  batch_size: 4


data_paths:
  raw:
    target:
      csv: 'data/raw/burn'
      db_name: 'burn_points.db'
      table_name: 'burn_points'
  processed:
    LST: 'data/processed/LST'
    DTM: 'data/processed/elevation'
    NDVI: 'data/processed/NDVI'
    wind_speed : 'data/processed/wind_speed'
    wind_dir_u : 'data/processed/wind_dir_WE'
    wind_dir_v : 'data/processed/wind_dir_SN'
    target: 'data/processed/burn'

    

data_sets:
  path: "data/datasets"